### ISSUE TITLE
QQ音乐（龙芯应用合作社版）无法通过liblol使用

### ISSUE THREAD

**Issue by dg1vg4** [AOSC-Dev/liblol#11]
操作系统 deepin v23 loong64 Preview
尝试过重打包，添加过liblol,liblol-dkms的依赖，但就是跑不起来。
不过有条件希望能直接支持QQ音乐官方的最新版Linux客户端。

**Comment by MingcongBai** [comment]
您好，

QQ 音乐需要使用 --no-sandbox 参数运行，这是已知问题；我们无法重新打包，因为腾讯未授权的情况下，我们不能重新分发 QQ 音乐

**Comment by MingcongBai** [comment]
啊抱歉，乌龙了：QQ 音乐没有龙架构原生版，只有 LATX 转译的

LATX 相关问题请到 https://github.com/deuso/latx-build 报告

**Comment by dg1vg4** [comment]
> 啊抱歉，乌龙了：QQ 音乐没有龙架构原生版，只有 LATX 转译的
> 
> LATX 相关问题请到 https://github.com/deuso/latx-build 报告

好吧，没想到龙芯应用合作社跑的是LATX
