### ISSUE TITLE
浙政钉不能在新世界运行

### ISSUE THREAD

**Issue by hzleihuan** [AOSC-Dev/liblol#6]
https://www.ding.zj.gov.cn/ 。感谢liblol新世界wps 龙芯浏览器一切ok ，但这个浙江用的im不行。报各种so缺少。（用的kylin版本。uos一样）

**Comment by MingcongBai** [comment]
您好，感谢报告，不过我发现没法下载这个软件…… 是对网络有什么要求吗？

**Comment by hzleihuan** [comment]
> 您好，感谢报告，不过我发现没法下载这个软件…… 是对网络有什么要求吗？
方便留QQ不 我的7581276

**Comment by MingcongBai** [comment]
好嘞，我这就联系您

**Comment by MingcongBai** [comment]
经查，该问题由两方面因素导致：一是新世界系统已经自带更新版本的 libsasl2（sover 为 3，而该程序需要 2），二是内建的 libm 和 libfreetype 库导致兼容性问题

建议解决办法如下：

1. 从 Loongnix 源下载旧版 libsasl2：`wget https://pkg.loongnix.cn/loongnix/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.27%2Bdfsg-1%2Bdeb10u1.1.lnd.1_loongarch64.deb`
2. 解压该包：`dpkg -x libsasl2-2_2.1.27+dfsg-1+deb10u1.1.lnd.1_loongarch64.deb temp`，如无 dpkg，则 `ar xv libsasl2-2_2.1.27+dfsg-1+deb10u1.1.lnd.1_loongarch64.deb && mkdir -v temp && tar xvf data.tar.xz -C temp`
3. 复制兼容库：`sudo cp -v temp/usr/lib/loongarch64-linux-gnu/libsasl2.so.2* /opt/lol/lib/loongarch64/aosc-linux-gnuow/`
4. 删除内含库：`sudo rm -v /opt/apps/com.zjd.gov/files/2.13.3-Release.5/lib{m,freetype}.so*`

**Comment by MingcongBai** [comment]
@hzleihuan 如有条件（考虑到您可能和开发商能直接沟通），还请转达如下意见：

1. 不要内包 libm 和 libfreetype/libfontconfig 等库，没有必要，而且很容易在系统更新后造成不兼容性
2. 内包一份 libsasl2，这在新世界系统里不太可能还有 sover 是 2（即 libsasl2.so.2 中的 2）的版本（现在都是 3，即 libsasl2.so.3）
3. 基于第二点，提供旧版本的 SASL2 库实际上有安全风险，建议尽快迁移到 sover 为 3 的更新版本

**Comment by MingcongBai** [comment]
该问题在普通版钉钉上也能复现

![Uploading image.png…]()

**Comment by hzleihuan** [comment]
除了以上再加上，1从 Loongnix 源下载旧版 liblber.so.2：wget  https://pkg.loongnix.cn/loongnix/pool/main/o/openldap/libldap-2.4-2_2.4.47%2Bdfsg-3%2Bdeb10u2.lnd.2_loongarch64.deb 
解压该包：dpkg -x libldap-2.4-2_2.4.47+dfsg-3+deb10u2.lnd.2_loongarch64.deb temp， 
复制兼容库：sudo cp -v temp/usr/lib/loongarch64-linux-gnu/* /opt/lol/lib/loongarch64/aosc-linux-gnuow/
 浙政钉成功运行，环境为archlinux+mate谢谢

**Comment by shankerwangmiao** [comment]
> 除了以上再加上，1从 Loongnix 源下载旧版 liblber.so.2：wget https://pkg.loongnix.cn/loongnix/pool/main/o/openldap/libldap-2.4-2_2.4.47%2Bdfsg-3%2Bdeb10u2.lnd.2_loongarch64.deb 解压该包：dpkg -x libldap-2.4-2_2.4.47+dfsg-3+deb10u2.lnd.2_loongarch64.deb temp， 复制兼容库：sudo cp -v temp/usr/lib/loongarch64-linux-gnu/* /opt/lol/lib/loongarch64/aosc-linux-gnuow/ 浙政钉成功运行，环境为archlinux+mate谢谢

我们今天发布了 0.1.3 版本。其改进是：将 liblol 提供的运行库提前优先于应用程序 `RPATH` 和 `LD_LIBRARY_PATH` 变量指定的库加载。这样，浙政钉可以在不修改程序内容的情况下运行。

0.1.3 版本预留了 `/opt/lol/local/preload-lib` 路径，提供给用户存放需要优先加载的运行库；另外预留了 `/opt/lol/local/lib`，提供给用户存放其它需要加载的运行库。

在 AOSC 上，通过在上述目录中创建适当的软连接（如下图所示），即可正常运行无修改的浙政钉程序。


![IMAGE 2024-01-22 12:59:48](https://github.com/AOSC-Dev/liblol/assets/6825907/5e003871-6221-44ac-886d-7c65bf208f0d)
