### ISSUE TITLE
新世界运行wps，各组件正常，除了wps pdf

### ISSUE THREAD

**Issue by hzleihuan** [AOSC-Dev/liblol#7]
无论是桌面快捷方式，还是终端/usr/bin/wpspdf ，都不能启动。没有任何反应，没有报错。环境为archlinux+ liblol0.1.2-1

**Comment by hzleihuan** [comment]
wps 版本为11.1.0.11711

**Comment by shankerwangmiao** [comment]
我这里直接执行 `/opt/kingsoft/wps-office/office6/wpspdf` 是可以正常打开的。系统是 AOSC。

**Comment by shankerwangmiao** [comment]
我又测试了一下，直接通过快捷方式启动也是正常的。

<img width="1988" alt="image" src="https://github.com/AOSC-Dev/liblol/assets/6825907/e4a570ce-20c9-46ac-ae32-0658e9e6af4b">

**Comment by ziqi-cn** [comment]
wps pdf 依赖libtiff5，需手动安装
https://wiki.archlinuxcn.org/wiki/WPS_Office#wpspdf_%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80_PDF_%E6%96%87%E4%BB%B6
